kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworldapp
  ports:
  - protocol: TCP
    port: 3333
    nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp-deployment
  labels:
    app: helloworldapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp
      track: stable
  template:
    metadata:
      labels:
        app: helloworldapp
        track: stable
    spec:
      containers:
      - name: helloworldapp
        image: ahmedsaleem/helloworldapp:latest
        ports:
        - containerPort: 3333
